# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_puzzle'),
    ]

    operations = [
    ]
