# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_auto_20160106_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='size',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
