# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0005_auto_20160106_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='id',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
