# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_load_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.Puzzle'),
        ),
    ]
